#!/bin/sh

case "$1" in
  start)
    echo "Starting aesdsocket daemon"
    start-stop-daemon -S -x /usr/bin/aesdsocket -- -d
    ;;
  stop)
    echo "Stopping aesdsocket daemon"
    start-stop-daemon -K -x /usr/bin/aesdsocket
    ;;
  *)
    echo "Usage: $0 {start | stop}"
    exit 1
esac
exit 0
